export const ENV = {
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_SUBACCOUNT_AUTH_TOKEN_MASTER_KEY:
    process.env.TWILIO_SUBACCOUNT_AUTH_TOKEN_MASTER_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  GOOGLE_TOKENS_MASTER_KEY: process.env.GOOGLE_TOKENS_MASTER_KEY,
} as const;
