export const ENV = {
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_SUBACCOUNT_AUTH_TOKEN_MASTER_KEY:
    process.env.TWILIO_SUBACCOUNT_AUTH_TOKEN_MASTER_KEY,
} as const;
